#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libstoragemgmt
Version  : 1.9.6
Release  : 45
URL      : https://github.com/libstorage/libstoragemgmt/releases/download/1.9.6/libstoragemgmt-1.9.6.tar.gz
Source0  : https://github.com/libstorage/libstoragemgmt/releases/download/1.9.6/libstoragemgmt-1.9.6.tar.gz
Summary  : Storage array management library
Group    : Development/Tools
License  : LGPL-2.0+ LGPL-2.1
BuildRequires : chrpath
BuildRequires : openssl-dev
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(python3)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pypi(pywbem)
BuildRequires : yajl-dev
Patch1: no-var-run.patch

%description
The libStorageMgmt library will provide a vendor agnostic open source storage
application programming interface (API) that will allow management of storage
arrays.  The library includes a command line interface for interactive use and
scripting (command lsmcli).  The library also has a daemon that is used for
executing plug-ins in a separate process (lsmd).

%prep
%setup -q -n libstoragemgmt-1.9.6
cd %{_builddir}/libstoragemgmt-1.9.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672183409
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --with-python3
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1672183409
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libstoragemgmt
cp %{_builddir}/libstoragemgmt-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/libstoragemgmt/448ab4f9f4c0c4f5b7eea423fabe48c1aba4f96f
%make_install

%files
%defattr(-,root,root,-)
