#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libstoragemgmt
Version  : 1.6.1
Release  : 2
URL      : https://github.com/libstorage/libstoragemgmt/archive/1.6.1.tar.gz
Source0  : https://github.com/libstorage/libstoragemgmt/archive/1.6.1.tar.gz
Summary  : Storage array management library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libstoragemgmt-bin
Requires: libstoragemgmt-python3
Requires: libstoragemgmt-config
Requires: libstoragemgmt-lib
Requires: libstoragemgmt-doc
Requires: libstoragemgmt-python
BuildRequires : chrpath
BuildRequires : openssl-dev
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(python2)
BuildRequires : pkgconfig(python3)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : ply
BuildRequires : procps-ng
BuildRequires : pyaml
BuildRequires : pyudev
BuildRequires : pywbem
BuildRequires : six
BuildRequires : valgrind
BuildRequires : yajl-dev

%description
libStorageMgmt : A library for storage management
Full documentation can be found at:
http://libstorage.github.io/libstoragemgmt-doc/

%package bin
Summary: bin components for the libstoragemgmt package.
Group: Binaries
Requires: libstoragemgmt-config

%description bin
bin components for the libstoragemgmt package.


%package config
Summary: config components for the libstoragemgmt package.
Group: Default

%description config
config components for the libstoragemgmt package.


%package dev
Summary: dev components for the libstoragemgmt package.
Group: Development
Requires: libstoragemgmt-lib
Requires: libstoragemgmt-bin
Provides: libstoragemgmt-devel

%description dev
dev components for the libstoragemgmt package.


%package doc
Summary: doc components for the libstoragemgmt package.
Group: Documentation

%description doc
doc components for the libstoragemgmt package.


%package lib
Summary: lib components for the libstoragemgmt package.
Group: Libraries

%description lib
lib components for the libstoragemgmt package.


%package python
Summary: python components for the libstoragemgmt package.
Group: Default
Requires: libstoragemgmt-python3

%description python
python components for the libstoragemgmt package.


%package python3
Summary: python3 components for the libstoragemgmt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libstoragemgmt package.


%prep
%setup -q -n libstoragemgmt-1.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513210500
%autogen --disable-static --with-python3
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1513210500
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/arcconf_lsmplugin
/usr/bin/hpsa_lsmplugin
/usr/bin/local_lsmplugin
/usr/bin/lsmcli
/usr/bin/lsmd
/usr/bin/megaraid_lsmplugin
/usr/bin/nfs_lsmplugin
/usr/bin/nstor_lsmplugin
/usr/bin/ontap_lsmplugin
/usr/bin/sim_lsmplugin
/usr/bin/simc_lsmplugin
/usr/bin/smispy_lsmplugin
/usr/bin/targetd_lsmplugin

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/libstoragemgmt.service

%files dev
%defattr(-,root,root,-)
/usr/include/libstoragemgmt/libstoragemgmt.h
/usr/include/libstoragemgmt/libstoragemgmt_accessgroups.h
/usr/include/libstoragemgmt/libstoragemgmt_battery.h
/usr/include/libstoragemgmt/libstoragemgmt_blockrange.h
/usr/include/libstoragemgmt/libstoragemgmt_capabilities.h
/usr/include/libstoragemgmt/libstoragemgmt_common.h
/usr/include/libstoragemgmt/libstoragemgmt_disk.h
/usr/include/libstoragemgmt/libstoragemgmt_error.h
/usr/include/libstoragemgmt/libstoragemgmt_fs.h
/usr/include/libstoragemgmt/libstoragemgmt_hash.h
/usr/include/libstoragemgmt/libstoragemgmt_local_disk.h
/usr/include/libstoragemgmt/libstoragemgmt_nfsexport.h
/usr/include/libstoragemgmt/libstoragemgmt_plug_interface.h
/usr/include/libstoragemgmt/libstoragemgmt_pool.h
/usr/include/libstoragemgmt/libstoragemgmt_snapshot.h
/usr/include/libstoragemgmt/libstoragemgmt_systems.h
/usr/include/libstoragemgmt/libstoragemgmt_targetport.h
/usr/include/libstoragemgmt/libstoragemgmt_types.h
/usr/include/libstoragemgmt/libstoragemgmt_version.h
/usr/include/libstoragemgmt/libstoragemgmt_volumes.h
/usr/lib64/libstoragemgmt.so
/usr/lib64/pkgconfig/libstoragemgmt.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libstoragemgmt.so.1
/usr/lib64/libstoragemgmt.so.1.6.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
